dataset:
  create_data: false
  samples_size: 40000
  save_dataset: false
  train_test_ratio: 0.025
  true_doa_test: null
  true_doa_train: null
  true_range_test: null
  true_range_train: null
evaluation:
  augmented_methods: []
  models: {}
  subspace_methods:
  - 2D-MUSIC
  - Beamformer
model:
  dcd_music: null
  model_type: SubspaceNet
  subspacenet: null
scenario_dict: {}
simulation_commands:
  create_data: false
  evaluate_mode: true
  load_model: false
  plot_acc_results: true
  plot_loss_results: true
  plot_results: true
  save_dataset: false
  save_model: false
  save_plots: false
  save_to_file: false
  train_model: false
system_model:
  M: 2
  N: 127
  T: 100
  bias: 0.0
  doa_range: 60
  doa_resolution: 1
  eta: 0.0
  field_type: NEAR
  max_range_ratio_to_limit: 0.5
  range_resolution: 1
  signal_nature: NON_COHERENT
  signal_type: NARROWBAND
  snr: 10.0
  sv_noise_var: 0.0
  wavelength: 0.06
training:
  batch_size: 32
  epochs: 50
  gamma: 0.5
  learning_rate: 0.001
  optimizer: ADAM
  scheduler: REDUCELRONPLATEAU
  simulation_name: null
  step_size: 50
  training_objective: angle, range
  use_wandb: false
  weight_decay: 1.0e-09
